<?php

namespace ARV\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    public function count()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(a)')
            ->from('ARVBlogBundle:Article', 'a');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    public function search($search)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('ARVBlogBundle:Article', 'a')
            ->where("a.title LIKE :search")
            ->orWhere("a.content LIKE :search")
            ->setParameter('search', '%' . $search . '%');

        return $qb->getQuery()->getResult();
    }

}
