<?php

namespace ARV\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{

    /**
     * Count number of articles.
     * @return int
     */
    public function count()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(a)')
            ->from('ARVBlogBundle:Article', 'a');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Search articles with $search.
     * @param $search
     * @param $publishedOnly
     * @return array
     */
    public function search($search, $publishedOnly)
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('a')
            ->from('ARVBlogBundle:Article', 'a')
            ->where("a.title LIKE :search")
            ->orWhere("a.content LIKE :search")
            ->orderBy('a.datePublication', 'DESC')
            ->setParameter('search', '%' . $search . '%');

        if ($publishedOnly) {
            $qb->andWhere('a.datePublication < :now')
                ->setParameter('now', new \DateTime());
        }

        return $qb->getQuery()->getResult();
    }

}
