<?php

namespace ARV\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{

    /**
     * Count number of comments.
     * @return int
     */
    public function count()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(c)')
            ->from('ARVBlogBundle:Comment', 'c');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

}
