<?php

namespace ARV\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    /**
     * Count number of tags.
     * @return int
     */
    public function count()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(t)')
            ->from('ARVBlogBundle:Tag', 't');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

    /**
     * Get tags for cloud.
     * @return array
     */
    public function getCloud() {
        // On passe par le QueryBuilder vide de l'EntityManager pour l'exemple
        $qb = $this->_em->createQueryBuilder();

        $qb->select('a')
            ->from('ARVBlogBundle:Article', 'a');
        $articles = $qb->getQuery()->getResult();
        $tags = array();
        foreach ($articles as $key => $article) {
            foreach($article->getTags() as $tag) {
                if (array_key_exists($tag->getName(), $tags)) {
                    $tags[$tag->getName()] ++;
                } else {
                    $tags[$tag->getName()] = 1;
                }
            }
//            $counts = array_count_values(explode(' ', $article->getTags()));
//            foreach ($counts as $k => $count) {
//                if (array_key_exists($k, $tags)) {
//                    $tags[$k] = $count + $tags[$k];
//                } else {
//                    $tags[$k] = $count;
//                }
//            }
        }


        return $tags;
    }

}
