<?php

namespace ARV\BlogBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{

    public function count()
    {
        $qb = $this->_em->createQueryBuilder();
        $qb->select('COUNT(t)')
            ->from('ARVBlogBundle:Tag', 't');

        return (int)$qb->getQuery()->getSingleScalarResult();
    }

}
