arv_blog_article_manage:
    path:     /admin
    defaults: { _controller: "ARVBlogBundle:Article:manage" }

arv_blog_article_list:
    path:     /liste-{search}/{page}
    defaults: { _controller: "ARVBlogBundle:Article:list", search: '', page: 1 }
    requirements:
        page: \d+

arv_blog_article_show:
    path:     /{id}-{slug}
    defaults: { _controller: "ARVBlogBundle:Article:show" }
    requirements:
        id: \d+

arv_blog_article_new:
    path:     /nouveau
    defaults: { _controller: "ARVBlogBundle:Article:new" }

arv_blog_article_create:
    path:     /creer
    defaults: { _controller: "ARVBlogBundle:Article:create" }
    methods:  [POST]

arv_blog_article_edit:
    path:     /{id}-{slug}/modifier
    defaults: { _controller: "ARVBlogBundle:Article:edit" }
    requirements:
        id: \d+

arv_blog_article_update:
    path:     /{id}-{slug}/mettre-a-jour
    defaults: { _controller: "ARVBlogBundle:Article:update" }
    methods:  [POST, PUT]
    requirements:
        id: \d+

arv_blog_article_delete:
    path:     /{id}-{slug}/supprimer
    defaults: { _controller: "ARVBlogBundle:Article:delete" }
    methods:  [POST, DELETE]
    requirements:
        id: \d+
