arv_blog_tag_manage:
    path:     /admin
    defaults: { _controller: "ARVBlogBundle:Tag:manage" }

arv_blog_tag_show:
    path:     /{id}
    defaults: { _controller: "ARVBlogBundle:Tag:show" }
    requirements:
        id: \d+

arv_blog_tag_new:
    path:     /nouveau
    defaults: { _controller: "ARVBlogBundle:Tag:new" }

arv_blog_tag_create:
    path:     /creer
    defaults: { _controller: "ARVBlogBundle:Tag:create" }
    methods:  [POST]

arv_blog_tag_edit:
    path:     /{id}/modifier
    defaults: { _controller: "ARVBlogBundle:Tag:edit" }
    requirements:
        id: \d+

arv_blog_tag_update:
    path:     /{id}/mettre-a-jour
    defaults: { _controller: "ARVBlogBundle:Tag:update" }
    methods:  [POST, PUT]
    requirements:
        id: \d+

arv_blog_tag_delete:
    path:     /{id}/supprimer
    defaults: { _controller: "ARVBlogBundle:Tag:delete" }
    methods:  [POST, DELETE]
    requirements:
        id: \d+

